### ISSUE TITLE
Including MathJax

### ISSUE THREAD

**Issue by hkortier** [trungleduc/nb_offline_convert#1]
The current implementation seeks for a specific MathJax config: `TeX-AMS_CHTML` it would be nice to support `Tex-MML-AM_CHTML` as well.

https://github.com/trungleduc/nb_offline_convert/blob/eed4ba8b6edd94376f61fdc32d74bf72ed039810/nb_offline_convert/tools.py#L65

**Comment by trungleduc** [comment]
Sure, I'll add it to the lib.

**Comment by trungleduc** [comment]
@hkortier `nb_offline_convert` [0.1.1](https://pypi.org/project/nb-offline-convert/0.1.1/) is released with configurable `Mathjax` config.
